### ISSUE TITLE
Cake.Frosting usage

### ISSUE THREAD

**Issue by jakubsuchybio** [cake-contrib/Cake.BuildSystems.Module#72]
Hi, can you please update your readme how to use this module with Cake.Frosting?
I tried it multiple times differently and I couldn't find out how to make this module working.
Until I found .UseModule extension on CakeHost so this works:
```csharp
            return new CakeHost()
                .InstallTool(new Uri("nuget:?package=xunit.runner.console&version=2.4.1"))
                .UseModule<TeamCityModule>()
                .UseContext<BuildContext>()
                .Run(args);
```

**Comment by nils-a** [comment]
@jakubsuchybio I have added a [real simple demo](https://github.com/cake-contrib/Cake.BuildSystems.Module/blob/616a12691985b693994fed623d9ca8868c7b3072/demo/frosting/build/Program.cs#L15), and a [minimal example, as well as some background for Cake.Frosting](https://github.com/cake-contrib/Cake.BuildSystems.Module/blob/616a12691985b693994fed623d9ca8868c7b3072/README.md#cakefrosting) in the readme.
Let me know if you think more information is needed.

fixed in #73
